name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          REACT_APP_OPEN_AI_API_KEY: ${{ secrets.REACT_APP_OPEN_AI_API_KEY }}
          REACT_APP_SPEECH_FLOW_KEY_ID: ${{ secrets.REACT_APP_SPEECH_FLOW_KEY_ID }}
          REACT_APP_SPEECH_FLOW_KEY_SECRET: ${{ secrets.REACT_APP_SPEECH_FLOW_KEY_SECRET }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          secrets: inherit